[package]
name = "litesvm-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
litesvm = "0.3.0"
solana-sdk = "~2.0.5"
spl-token = { version = "6.0.0", features = ["no-entrypoint"] }
spl-associated-token-account = "5.0.1"
bytemuck = "1.18.0"

[dev-dependencies]